### ISSUE TITLE
ACF addon not working

### ISSUE THREAD

**Issue by mellyna** [jcollings/importwp-woocommerce#1]
Hi ! I'm using ImportWP Pro which came bundled in Rehub theme in wordpress. 

1/I installed ACF addon plugin but nothing changed in the fields available in the tool. No ACF field... Everything is up to date and I have no issues with woocommerce and Yoast addons. Only with ACF. Do you know what can be the issue?

2/ Short description fields don't work for woocommerce products. 

Please help, thank you

**Comment by jcollings** [comment]
Hi Mellyna,

I have moved your issue onto the woocommerce addon repo, as it seems the latest version of importwp-woocommerce is not displaying the custom field section on the product importer template.

I am working on this and the short description issue and will update you when i have made progress

**Comment by mellyna** [comment]
Thank you James. Looking forward to hearing from you !

**Comment by jcollings** [comment]
I have released a pre release version of the plugin (v2.0.3) that can be found via the [releases](https://github.com/jcollings/importwp-woocommerce/releases/tag/2.0.3) section, this fixes the short description issue, and allows for the custom fields section to display if you are using ImportWP Pro.

An update has also been released for ImportWP ACF addon via the [releases](https://github.com/jcollings/importwp-advanced-custom-fields/releases/tag/2.0.3) section.

Please download and install both the latest version of importwp-acf and importwp-woocommerce, these together should hopefully fix your issues.

**Comment by mellyna** [comment]
Hi ! ACF fields and short descriptions now work perfectly, thank you !
However, a new issue came up : Product URL is no longer working when I set product as external. Can you take a look?

I have another issue with Yoast addon, none of these fields work with woocommerce products  : SEO title, meta description, focus keyphrase. I haven't tried social media fields but I guess the problem is the same.  
Thanks for your help

**Comment by jcollings** [comment]
Hi,

Can you please download the latest version of importwp-woocommerce this should fix the external product url and button text: https://github.com/jcollings/importwp-woocommerce/releases/tag/2.0.4

I have tried using the latest version of YoastSEO 15.2.1, and importwp-yoast 2.0.23 (https://github.com/jcollings/importwp-yoast-seo/releases/tag/2.0.23) , and i am able to import all yoast settings. Can you please try this latest release and let me know if it helps?

**Comment by mellyna** [comment]
Hi ! External URL and button text work perfectly, thank you !!

As for the Yoast issue, I already found another way to bulk edit my meta but I will import new products next week and I'll try again with the ImportWP addon.
Thanks again !
