### ISSUE TITLE
Problem of uploaded/mapping WooCommerce Product Taxomonies

### ISSUE THREAD

**Issue by cristan88** [jcollings/importwp-woocommerce#5]
Hello James, as per my earlier comment on Envato, here is a few of my screenshot for your information. To summarize, I tried to upload WC product taxomonies, however once upload completed, the Taxomonies (so far only the product custom attribute) doesn't work. Below is the screenshot by steps:

1. https://prnt.sc/124g23y
2. https://prnt.sc/124g3mp
3. https://prnt.sc/124g4lb
4. https://prnt.sc/124g56i
5. https://prnt.sc/124g9yn
6. https://prnt.sc/124gf7d
7. https://prnt.sc/124ggyb
8. https://prnt.sc/124gj7j
9. https://prnt.sc/124gkcs
10. https://prnt.sc/124gmgu

I then re-run the whole process, but this time I choose "create new field" but still it doesn't work
https://prnt.sc/124gi5d

Here is the file I tried to upload:
https://drive.google.com/file/d/14h9uCu5BWMUd8U2cXD30ibYsXWDe-JEq/view?usp=sharing

Do advise if I did anything wrong, cheers.

**Comment by jcollings** [comment]
Hi,

Thanks you for all the screenshots, they have been useful to know your setup.

Can you use the Product Attributes section instead of the Taxonomies section, and let me know how you get on (make sure yo remove the existing product attributes that you added from the taxonomies section so there are no duplicate).

James

**Comment by cristan88** [comment]
Hi James, thanks for the advice but I've failed to try it out due to there is a new issue:
https://prnt.sc/126hojm

Just a day ago such problem doesn't happen. I'm using the same account and I'm the administrator, why is "not enough permission"?

Thanks.

**Comment by jcollings** [comment]
That screenshot suggests that you have not given the importer the update permission, without this it cant update records.

**Comment by cristan88** [comment]
but it was working fine prior. May I know where does the permission need to be given? i tried to look at the ImportWP documentation but I cant find related topic

**Comment by jcollings** [comment]
There are 3 core permission types insert, update, and delete, these are related to what can happen when importing a record, if it can be created, modified, or deleted.

Based on one of your screenshots you can see that it was inserted, so if it already exists, then it needs to modify it, without the update permission it cant do this.

**Comment by cristan88** [comment]
thanks James, all is working well now, cheers.
